s3:
  host: ""
  region: "ru"
  access_key: ""
  secret_key: ""
  bucket: ""
server:
  port: 8000
  shutdown_timeout: 2
  size_upload: 1073741824
  api_key: ""
  delete_key: ""
health:
  check_interval: 10
cdn: ""
